TRAIN:
  DATASET: 'breakfast'
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: False
TEST:
  CHECKPOINT_PATH: ./experiments/breakfast/mstcn_progress_slot/checkpoint/1/best_checkpoint.pyth
DATA:
  CV_SPLIT_NUM: 1
  BACKGROUND_INDICES: [0]
SOLVER:
  BASE_LR: 0.00025
  MAX_EPOCH: 150
  WEIGHT_DECAY: 10e-4
  OPTIMIZING_METHOD: 'adam'
  LR_POLICY: 'constant_cosine_decay'
  WARMUP_EPOCHS: 15
  T_MAX: 180
MODEL:
  NAME: 'ms-tcn'
  LOSS_FUNC: 'ce_mse'
  MSE_LOSS_FRACTION: 0.17
  BCE_LOSS_FRACTION: 0.0
  BCE_WEIGHT: 0
  NUM_CLASSES: 48
  INPUT_DIM: 2048
  ACTION_MASK: False
  ACTION_SLOT: 0
  PROGRESS_SLOT: 5
  TCN:
    NUM_LAYERS: 10
    NUM_F_MAPS: 64
    NUM_STAGES: 4
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 115
LOG_PERIOD: 1500
OUTPUT_DIR: ./experiments/breakfast/mstcn_progress_slot