TRAIN:
  DATASET: 'assembly101'
  EVAL_SPLIT: 'val'
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
DATA:
  FRAME_SAMPLING_RATE: 1
SOLVER:
  BASE_LR: 0.00025
  MAX_EPOCH: 120
  WEIGHT_DECAY: 1e-3
  OPTIMIZING_METHOD: 'adam'
  LR_POLICY: 'constant_cosine_decay'
  WARMUP_EPOCHS: 15
  T_MAX: 120
MODEL:
  NAME: 'ltc'
  LOSS_FUNC: 'ce_mse'
  MSE_LOSS_FRACTION: 0.17
  NUM_CLASSES: 202
  INPUT_DIM: 2048
  LTC:
    NUM_LAYERS: 9
    NUM_STAGES: 4
    MODEL_DIM: 64
    WINDOWED_ATTN_W: 64
    LONG_TERM_ATTN_G: 64
    USE_INSTANCE_NORM: False
    CHANNEL_MASKING_PROB: 0.3
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
LOG_PERIOD: 100
OUTPUT_DIR: ./experiments/assembly101
